// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhl6na1VnGvdkbJ2Sq7PFxDA52SaIcmc',
    appId: '1:883182251476:web:a4fdb73ec5942feb5bfa41',
    messagingSenderId: '883182251476',
    projectId: 'routeplayground',
    authDomain: 'routeplayground.firebaseapp.com',
    storageBucket: 'routeplayground.appspot.com',
    measurementId: 'G-W29820G0MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwncxl9bWX_WgnLO6UMgGIcYA7UgqEc4',
    appId: '1:883182251476:android:20ffc1c3afffec575bfa41',
    messagingSenderId: '883182251476',
    projectId: 'routeplayground',
    storageBucket: 'routeplayground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpxyTbingnNrJ8DXt_QBgPDczqWHz3eKk',
    appId: '1:883182251476:ios:a570d1c818a2c29c5bfa41',
    messagingSenderId: '883182251476',
    projectId: 'routeplayground',
    storageBucket: 'routeplayground.appspot.com',
    iosClientId: '883182251476-sqhdstkrjfqatsmrmmi9qh1fkk4i8inc.apps.googleusercontent.com',
    iosBundleId: 'com.example.routePlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpxyTbingnNrJ8DXt_QBgPDczqWHz3eKk',
    appId: '1:883182251476:ios:a570d1c818a2c29c5bfa41',
    messagingSenderId: '883182251476',
    projectId: 'routeplayground',
    storageBucket: 'routeplayground.appspot.com',
    iosClientId: '883182251476-sqhdstkrjfqatsmrmmi9qh1fkk4i8inc.apps.googleusercontent.com',
    iosBundleId: 'com.example.routePlayground',
  );
}
